tarfin-labs/event-machine

- src/Definition/MachineDefinition.php
- src/Definition/StateDefinition.php
- tests/EntryActionsTest.php
- tests/InitialStateTest.php
- The default value of `$eventBehavior` in the `runEntryActions` method is set to `null`
- `runEntryActions` method is called for `initial` state definition in `buildInitialState`
> Initial state entry action fix

- src/Behavior/EventBehavior.php
- tests/EventTest.php
This commit adds a `version` property to the `EventBehavior` class in the `Behavior/EventBehavior.php` file. The `version` property allows specifying the version of an event.
- Added a new property `version` with type `int` to the `EventBehavior` class.
- Updated the constructor to accept the `version` parameter.
- Added a default value of `1` for the `version` property.
- Created a new test file `tests/EventTest.php` to test the `version` property of events.
- Added a test to check that events without an explicit version definition have a default version of `1`.
- Added a test to check that events with an explicit version definition have the specified version.
> feat: Add `version` property to `EventBehavior` (WEB-3699)

- src/Behavior/EventBehavior.php
feat: Update `EventBehavior` constructor with optional `version` parameter (WEB-3701)
This commit updates the constructor of the `EventBehavior` class in the `Behavior/EventBehavior.php` file. The constructor now includes an optional `version` parameter, allowing flexibility in specifying the version of an event.
- Added an optional parameter `version` of type `int` to the `EventBehavior` constructor.
- The `version` parameter defaults to `1` if not provided.
- This change provides more flexibility when creating instances of `EventBehavior` by allowing the version to be optionally specified.
> feat: Update `EventBehavior` constructor with optional `version` parameter (WEB-3701)

- database/migrations/create_machine_table.php.stub
- src/Actor/State.php
- src/Behavior/EventBehavior.php
- src/Definition/InternalEvent.php
- src/Definition/MachineDefinition.php
- src/Definition/SourceType.php
- src/Definition/StateDefinition.php
- src/Definition/TransitionBranch.php
- src/Definition/TransitionDefinition.php
- src/Models/MachineEvent.php
- tests/EventStoreTest.php
Added `source` column to `machine_events` table
Added `setInternalEventBehavior` method to `State`
Added `SourceType` enum
Added `source` column to `MachineEvent` model
Added `source` parameter to `EventBehavior`
Added `$state` parameter to `runExitActions` method in `StateDefinition`
Added `$state` parameter to `runActions` method in `TransitionBranch`
Added `$state` parameter to `runAction` method in `MachineDefinition`
Added `machine.initial` internal event
Added internal events for action
Added internal events for guard
The use of `setEventBehavior` in the `Transition` method has been relocated.
Removed `$context` param from `runEntryActions`, `runExitActions`, `runActions`, `runAction`, `getFirstValidTransitionBranch` methods
> WEB-3703: Introduce Internal Events

- src/Actor/MachineActor.php
This commit refactors the `send()` method in the `MachineActor` class. Instead of returning the new state directly from the `transition()` method, the new state is now assigned to the `state` property of the `MachineActor` class.
Previously, the `send()` method would return the new state as the result of the `transition()` method. This approach required the caller to capture the returned state and assign it manually. In this commit, the `send()` method is updated to assign the new state directly to the `state` property, eliminating the need for an additional assignment statement.
> fix(MachineActor): Update `send()` method to assign the new state (WEB-3747)

- src/Actor/State.php
This commit refactors the event type placeholder formatting in the `State` class. Previously, the placeholder value was directly passed to the `sprintf` function, resulting in the full class name being used.
The change introduces the use of the `class_basename` function from the `Illuminate\Support\Str` class to extract the base name of the class from the placeholder value. This improves the readability and conciseness of the event type representation.
> refactor(State): Record internal event types as base class names instead of FQCN (WEB-3761)

- src/ContextManager.php
- tests/ContextManagerTest.php
Implemented magic methods __set, __get, and __isset in ContextManager class to streamline usage and improve readability of code. These methods enable direct property-like interaction with ContextManager objects. Additionally, test cases were written to confirm their correct functionality.
> test: Add magic methods to ContextManager and tests (WEB-3802)

- src/ContextManager.php
- tests/ContextManagerTest.php
This commit enhances the `has()` method in the `ContextManager` class. Previously, this method only checked if a key exists in the context. Now, it can also check if the value associated with the key is of a specified type. If a type is not provided, the method only checks for the existence of the key.
Test cases in `ContextManagerTest` have also been added to verify this new functionality.
> feat(ContextManager): Add type checking to `has()` method (WEB-3803)

- src/Definition/TransitionBranch.php
- tests/GuardedActionsTest.php
In the TransitionBranch class, a new description field has been added. This field is set based on the 'description' values in the transitionBranchConfig array. This change was made to provide a mechanism for having more descriptive data associated with transition branches. This newly added description field is also tested in GuardedActionsTest to ensure it works as expected.
> feat(TransitionBranch): Add description field (WEB-3816)

- src/Behavior/ActionBehavior.php
- tests/ActionTest.php
Two test cases have been added in the ActionTest file to check if actions can return values. A new method 'multipleWithItselfAction' was introduced with this functionality. The ActionBehavior interface has also been updated to reflect this change in the functioning of actions. This additional functionality was needed to provide more flexibility in the use of actions within the EventMachine framework.
> Add functionality for actions to return values (WEB-3823)

- src/Actor/MachineActor.php
- tests/MachineActorSerializationTest.php
- tests/Stubs/Models/ModelA.php
The MachineActor class now implements JsonSerializable, enabling it to represent an object in serialized format for use in ModelA attribute serialization. Additionally, a new test file, MachineActorSerializationTest.php, is added to ensure the correct functionality of this new serialization ability. The ModelA class has also been updated to use HasFactory for testing convenience. This improves our testing capabilities and the flexibility in working with MachineActor instances.
> feat: Add JSON serialization to MachineActor and test (WEB-3841)

- src/Factories/EventFactory.php
(WEB-3873) refactor!(EventFactory): Do not validate event behavior after building an Event Behavior 
The method call in EventFactory class has been changed from `validateAndCreate` to `from` in order to reflect the update in EventBehavior model's functionality. This change allows the usage of more flexible attribute sets for model instances.
> refactor!(EventFactory): Do not validate event behavior after building an Event Behavior 

- src/Behavior/EventBehavior.php
- tests/EventValidationTest.php
- tests/Stubs/Events/ValidatedEvent.php
This commit adds a new method `stopOnFirstFailure` to the `EventBehavior` class. This method indicates whether the validator should stop on the first rule failure. By default, it returns true. Developers can override this method in subclasses to change this behavior.
> Web 5120 form request siniflarinda bail ifadesinin kaldirilmasi ve stop on first failure ozelliginin kullanilmasi

- src/Behavior/InvokableBehavior.php
Updated type matching logic to use is_a and is_subclass_of for more accurate type resolution. This ensures that the correct context is selected based on class and subclass hierarchies, enhancing code reliability and maintainability.
> WB-338: Improve type resolution in InvokableBehavior

- src/Behavior/InvokableBehavior.php
- tests/RequiredContextTest.php
- tests/Stubs/Actions/IsOddAction.php
- tests/Stubs/Guards/IsOddGuard.php
- tests/Stubs/Guards/IsValidatedOddGuard.php
The `InvokableBehavior` class provides context validation functionality through `hasMissingContext()` and `validateRequiredContext()` methods. These methods were instance-based but did not rely on any instance state since they only validate required context types against provided context values.
- Made `$requiredContext` property static in `InvokableBehavior` class and its subclasses
- Converted `hasMissingContext()` and `validateRequiredContext()` to static methods
- Updated test helper classes to use static `$requiredContext`
- Refactored tests to use static method calls instead of creating instances
- Added comprehensive test cases for all context validation scenarios
- More logical API: Since validation is class-based (defined by `$requiredContext` in each behavior class) rather than …
> Wb 624 event machine convert context validation methods to static in invokable behavior class

- src/Actor/Machine.php
- src/Traits/ResolvesBehaviors.php
- tests/ResolveInlineBehaviorTest.php
- tests/Stubs/Machines/OrderMachine.php
This PR introduces the `ResolvesBehaviors` trait that enables direct testing of inline behaviors defined within machine definitions. This enhancement significantly improves testability of state machine components by allowing developers to access and test behaviors without instantiating the entire machine.
- Direct access to calculator behaviors via `getCalculator()`
- Direct access to guard behaviors via `getGuard()`
- Direct access to action behaviors via `getAction()`
- Direct access to event behaviors via `getEvent()`
- Type-safe behavior resolution with proper return types
- Clear error handling with `BehaviorNotFoundException`
```php
// Testing a calculator behavior
$calculator = OrderMachine::getCalculator('calculateTotal');
$context = new ContextManager(['count' => 5]); …
```
> Wb 707 event machine enable testing of inline behaviors in machine definitions

- src/Definition/MachineDefinition.php
- src/Definition/TransitionDefinition.php
- src/StateConfigValidator.php
- tests/StateConfigValidatorTest.php
- tests/StateDefinitionTypeTest.php
Introduces strict validation for state machine configurations through the new `StateConfigValidator` class, ensuring consistency and early error detection.
- Add validation for root-level machine configuration
- Validate state properties and transitions
- Enforce proper structure for guards and actions
- Improve error messages for configuration issues
Example usage in machine definitions:
```php
MachineDefinition::define([
'id' => 'order',
'initial' => 'pending',
'states' => [
'pending' => [
'on' => {
'APPROVE' => [
'target' => 'approved',
'guards' => 'isValid'  // Now validated
]
}
]
]
]);
```
The validator checks for:
- Valid keys at each configuration level
- Proper structure for transitions and guards
- Correct state type definitions
- Valid entry/exit actions format
Any configuration …
> Validation for State Machine Configuration Structure

- tests/CalculatorsWithGuardedTransitions.php
Currently, it's unclear how calculators behave in guarded transitions, especially when multiple branches are involved. We need comprehensive tests to document and verify the exact execution order and behavior of calculators within guarded transitions. This will help us to  better understand the system's behavior and prevent potential misuse of calculators in state machine definitions
> Add tests to verify calculator execution behavior in guarded transitions

- src/Commands/GenerateUmlCommand.php
- src/Commands/MachineConfigValidatorCommand.php
- src/MachineServiceProvider.php
- tests/CommandTest.php
- tests/Commands/MachineConfigValidatorCommandTest.php
- tests/Pest.php
- tests/StateDefinitionTest.php
Adds a new console command `machine:validate` to validate machine configurations before runtime. The command can:
- Validate a specific machine: `machine:validate MyMachine`
- Validate multiple machines: `machine:validate MyMachine AnotherMachine` 
- Validate all machines: `machine:validate --all`
The command uses `StateConfigValidator` to check machine configurations for potential issues like invalid transitions, missing states, or incorrect type definitions.
Features:
- Works with short class names or FQNs
- Detailed error reporting
- Graceful error handling
Example usage:
```bash
php artisan machine:validate OrderMachine   # Single machine
php artisan machine:validate --all          # All machines
> Config validator command

- .github/workflows/pest.yml
- composer.json
- src/Transformers/ModelTransformer.php
- tests/StateTest.php
- **feat(dependencies): update PHP and package versions in composer.json**
- **feat(transformer): add TransformationContext parameter to transform method**
- **feat(workflow): update PHP and Laravel versions in Pest configuration**
> Laravel 12.x Compatibility
